package com.example.firstcompose.models_Schedule

data class ScheduleX(
    val arena_city: String,
    val arena_name: String,
    val arena_state: String,
    val bd: Bd,
    val buy_ticket: String,
    val buy_ticket_url: String,
    val cl: String,
    val cs_custom_fields: CsCustomFields,
    val custom_fields: Any,
    val game_state: String,
    val game_subtype: String,
    val gametime: String,
    val gcode: String,
    val gid: String,
    val h: H,
    val hide: Boolean,
    val is_game_necessary: String,
    val league_id: String,
    val logo_url: Any,
    val ppdst: String,
    val season_id: String,
    val seri: String,
    val st: Int,
    val stt: String,
    val template_fields: TemplateFields,
    val uid: String,
    val v: V,
    val year: Int
)